server: 
    port: ${PORT:8080}
    servlet:
        context-path: /bigfood

spring:
    profiles:
        include: local
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        defer-datasource-initialization: false
        database-platform: org.hibernate.dialect.MySQL8Dialect

    # Flyway Configuration
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration
        baseline-version: 0
        validate-on-migrate: true
        clean-disabled: true

    mail:
        host: ${mail_host}
        port: ${mail_port}
        username: ${mail_username}
        password: ${mail_password}
        properties:
            mail: 
                smtp:
                    auth: true
                    starttls:
                        enable: true

    main:
        banner-mode: "off"
    
    output:
        ansi:
            enabled: ALWAYS

logging:
    level:
        root: WARN 
        "com.example.bigfood": INFO
    pattern:
        console: "%d{HH:mm:ss.SSS} %-5level %msg%n"

# Springdoc OpenAPI Configuration
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
